# Netlify Configuration for Full-Stack App (Frontend + Backend)

# Build Settings
[build]
  base = "frontend"
  publish = "dist"
  command = "npm install && npm run build && cd ../netlify && npm install"
  functions = "../netlify/functions"

# Environment variables (set these in Netlify dashboard)
[build.environment]
  NODE_VERSION = "20"

# Redirect API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Function settings
[functions]
  node_bundler = "esbuild"
  included_files = ["../backend/src/**"]
